name: Build

on:
  workflow_dispatch:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: # Use archlinux since this makes getting the dependencies easier...
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup


    steps:
      - name: Checkout build scripts
        uses: actions/checkout@v2

      - name: Initialize ArchLinux
        run: |
          bash -e scripts/setup-archlinux.sh
          chown -R user .

      - name: Installing GIT
        run: sudo pacman -S --noconfirm git
        # the actions/checkout@v2 requires this to make an actual git clone.

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: verilatorjs

      - name: Find latest verilator release
        uses: oprypin/find-latest-tag@v1
        with:
          repository: verilator/verilator
        id: verilator

      - name: Compute new version
        run: bash -e scripts/check_and_compute_versions.sh "${{ steps.verilator.outputs.tag }}"
        id: version_check

      - name: Checkout latest verilator release
        if: ${{ steps.version_check.outputs.uptodate != 1 }}
        uses: actions/checkout@v2
        with:
          repository: verilator/verilator
          ref: ${{ steps.verilator.outputs.tag }}
          path: verilator

      - name: Setting up build environment
        if: ${{ steps.version_check.outputs.uptodate != 1 }}
        run: |
          . /etc/profile # set up PATH for emscripten
          bash -e scripts/setup_build.sh . verilator

      - name: Building verilator
        if: ${{ steps.version_check.outputs.uptodate != 1 }}
        run: |
          . /etc/profile # set up PATH for emscripten
          export MAKEFLAGS=-j$(nproc)
          bash -e scripts/build_verilator.sh . verilator

      - name: Update master branch
        if: ${{ steps.version_check.outputs.uptodate != 1 }}
        run: |
          mkdir -p verilatorjs/dist
          cp -v verilator/bin/verilator_bin verilatorjs/dist/verilator.js
          cp -v verilator/bin/verilator_bin.wasm verilatorjs/dist/
          cp verilator/LICENSE verilatorjs/

      - name: Installing npm
        if: ${{ steps.version_check.outputs.uptodate != 1 }}
        run: |
          sudo pacman -S --noconfirm npm

      - name: Updating version
        if: ${{ steps.version_check.outputs.uptodate != 1 }}
        run: |
          cd verilatorjs
          npm version ${{ steps.version_check.outputs.version }} --no-git-tag-version

      - name: Commit changes
        if: ${{ steps.version_check.outputs.uptodate != 1 }}
        run: |
          cd verilatorjs
          git config --global user.name 'Yichao Yu'
          git config --global user.email 'yuyichao@users.noreply.github.com'
          git status
          git add .
          git commit -m "Auto build of version ${{ steps.version_check.outputs.version }}"
          git tag "v${{ steps.version_check.outputs.version }}"
          git push --follow-tags
